Repository abassibe/Gomoku, pull requests merged in 2021-03, with the labels that each got.

#48 Feature/architecture revamp
  .gitignore
  Cargo.toml
  src/algorithm/minimax.rs
  src/algorithm/mod.rs
  src/bitboard.rs
  src/bitboard/axis.rs
  src/bitboard/direction.rs
  src/bitboard/mod.rs
  src/bitboard/new_pattern.rs
  src/bitboard/new_pattern/tests.rs
  src/bitboard/pattern.rs
  src/bitboard/pattern/tests.rs
  src/goban.rs
  src/goban/fscore.rs
  src/goban/heuristic.rs
  src/goban/mod.rs
  src/goban/tests.rs
  src/lib.rs
  src/node/mod.rs
  src/node/tests.rs
  src/stone.rs
Labels: help wanted

#49 Fix crash open 4
  src/algorithm/minimax.rs
  src/algorithm/mod.rs
  src/algorithm/tests.rs
  src/node/mod.rs
  src/node/tests.rs
Labels: enhancement

#50 Try to make fscore more accurate
  src/algorithm/minimax.rs
  src/algorithm/mod.rs
  src/algorithm/tests.rs
  src/lib.rs
Labels: enhancement

#54 Make the AI play more aggressively when no threats
  src/algorithm/minimax.rs
  src/algorithm/mod.rs
  src/bitboard/pattern.rs
  src/bitboard/pattern/tests.rs
  src/lib.rs
  src/node/mod.rs
  src/node/tests.rs
Labels: enhancement

#58 Fix the way bitboards are assigned to players
  src/algorithm/mod.rs
  src/bitboard/mod.rs
  src/bitboard/pattern/tests.rs
  src/lib.rs
Labels: bug

#59 Feature/negamax
  src/algorithm/minimax.rs
  src/algorithm/mod.rs
  src/algorithm/negamax.rs
  src/algorithm/tests.rs
  src/bitboard/pattern.rs
  src/bitboard/pattern/tests.rs
  src/goban/fscore.rs
  src/goban/heuristic.rs
  src/goban/mod.rs
  src/lib.rs
  src/node/mod.rs
Labels: enhancement

#61 Feature/transposition table
  Cargo.toml
  src/algorithm/minimax.rs
  src/algorithm/mod.rs
  src/algorithm/transposition_table.rs
  src/goban/fscore.rs
  src/goban/mod.rs
  src/lib.rs
  src/node/mod.rs
  start_gomoku.sh
Labels: enhancement
